name: Actions

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on ${{ runner.os }} server!"
      - uses: actions/checkout@v1
